### ISSUE TITLE
Task list: clock control

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#132]
In rough order of importance:

- [x] https://github.com/bittide/bittide-hardware/issues/209
  - [x] https://github.com/bittide/bittide-hardware/issues/203
  - [x] https://github.com/bittide/bittide-hardware/pull/199
- [x] https://github.com/bittide/bittide-hardware/issues/125
- [x] https://github.com/bittide/bittide-hardware/issues/206
- [x] https://github.com/google-research/bittide/issues/124

**Comment by martijnbastiaan** [comment]
All done :)
