### ISSUE TITLE
Q1 + Q2 milestones

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#271]
# Milestone 1
Clock control implementation on multiple, joined FPGA-based emulator board.

**This has been implemented and available under `bittide-instances/demo-files`**

## Demo

https://user-images.githubusercontent.com/5658854/228572080-3a1fd8cc-5198-454b-b2b8-293a433b71f0.mp4 

## Optional

 - [x] Get rid of Verilog wrappers
   - [x] https://github.com/bittide/bittide-hardware/issues/204
   - [X] https://github.com/clash-lang/clash-compiler/pull/2427
 - [x] Integrate demo into build flow
   - [x] https://github.com/bittide/bittide-hardware/issues/267
   - [x] https://github.com/bittide/bittide-hardware/issues/268

# Milestone 2
Integrate an external, pipelined, RV32IMC capable RISC-V core in a Bittide processing element. Core should be able to execute basic binaries booting a Bittide system.

TODO:
 - [X] Write Clash wrapper around VexRisc, https://github.com/clash-lang/clash-vexrisc.
 - [x] Demo. Printing Bittide ASCII art over UART.
 - [x] Integrate `clash-vexric` in processing element, https://github.com/bittide/bittide-hardware/pull/266

Optional: 

 - [x] https://github.com/bittide/bittide-hardware/issues/270
 - [x] https://github.com/bittide/bittide-hardware/issues/269

# Milestone 3
Demo: https://github.com/bittide/bittide-hardware/pull/308#issuecomment-1614771408

Develop an interconnected mesh of 9 Bittide domains. This mesh should be able to form the basis for clock control algorithm testing. Architecture should be reconfigurable as any subset of the interconnected mesh. _Note: we don't currently have all the hardware for exactly 9 boards, and it looks like its pretty hard to source. 8 boards will work just fine._

TODO:
  - [x] https://github.com/bittide/bittide-hardware/issues/204
  - [x] Order remaining boards (4)
  - [x] Order SMA + optic fiber cables + SFP cages
  - [x] Investigate use of patch panel
  - [x] 3D print brackets
  - [x] https://github.com/bittide/bittide-hardware/issues/225 (except for last point)
  - [x] Bittide instance for fully connected Bittide domain

Nice to have:
  - [x] Demo using oscilloscopes

Optional:
  - [x] Output debug information + live plots
  - [ ] https://github.com/bittide/bittide-hardware/issues/228
  - [ ] Add manual clock overrides - that is; allow stress testing.
  - [x] Implement https://arxiv.org/abs/2303.11467 in hardware
  - [x] Implement simplified version of https://arxiv.org/abs/2303.11467
    - [x] https://github.com/clash-lang/clash-compiler/pull/2452

# Milestone 4
Software controlled clock control implementation, including automated testing with hardware in loop. This will be delivered as part of a clock control experimentation platform, accessible through GitHub Actions.

TODO:
  - [x] https://github.com/clash-lang/clash-vexriscv/pull/5
  - [x] https://github.com/bittide/bittide-hardware/issues/341
  - [x] https://github.com/bittide/bittide-hardware/issues/342
  - [x] https://github.com/bittide/bittide-hardware/issues/343
  - [x] https://github.com/bittide/bittide-hardware/issues/344
  - [x] Write hardware-in-loop test
  - [x] https://github.com/bittide/bittide-hardware/issues/345
  - [x] https://github.com/bittide/bittide-hardware/issues/225
  - [x] Add synchronization hardware / test

Nice to have:
  - [ ] https://github.com/bittide/bittide-hardware/issues/346
  - [ ] https://github.com/bittide/bittide-hardware/issues/353
  - [ ] Feed program over UART/ethernet

# Milestone 5
Increase debug-ability RISC-V cores: add GDB/OpenOCD integration, expose bittide runtime debug information, develop command line tooling code (or integration with existing tools) for debugging).

TODO: 
 - [x] Investigate whether we can reuse VexRiscv infrastructure
 - [ ] https://github.com/bittide/bittide-hardware/issues/410

Optional:
 - [x] https://github.com/bittide/bittide-hardware/issues/324
