### ISSUE TITLE
Q3 + Q4 milestones

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#414]
# Milestone 6
Implement use of I2C/SPI to program clock boards. We currently adjust clock boards using near-zero latency FINC/FDEC pins. These pins are only exposed for very specific chips, and even then the only off-the-shelf hardware we could buy required PCB modifications. We’ve since discovered that suitable clock adjustment chips are present on many FMC/SFP extension cards, though their FINC/FDEC functionality is only accessible over relatively slow protocols. If we can confirm (both in simulation and practice) that this doesn’t matter, we can greatly simplify our physical setup and reduce future hardware cost.

TODO:

- [ ] https://github.com/bittide/bittide-hardware/issues/411

# Milestone 7
Bound clock control: Clocks can currently adjust their clock frequencies without bounds. We should implement bounds and investigate its effect on clock stability

TODO:

- [x] https://github.com/bittide/bittide-hardware/issues/412
- [ ] https://github.com/bittide/bittide-hardware/issues/413 (depends on previous)

# Milestone 8
TBA
