### ISSUE TITLE
Remove dependency on test start order

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#638]
`SyncInSyncOut` currently crucially depends on the _last_ FPGA in the demo rig to be the last FPGA to have its HITL VIO start probe asserted. This prevents us from implementing parallel test start assertion.

# TODO
- [ ] Amend `SyncInSyncOut`
- [ ] Check whether there are any other tests that depend on this
- [ ] Remove ordering (add scrambling?) from test infrastructure
- [ ] Amend this issue with relevant code links after merging https://github.com/bittide/bittide-hardware/pull/536
